# Generated by Django 2.2.5 on 2019-09-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('postalCode', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
    ]
