# Generated by Django 2.2.6 on 2019-10-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postalcode', '0002_auto_20190927_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='postalCode',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
