# Generated by Django 2.2.6 on 2019-10-06 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postalcode', '0003_auto_20191006_0604'),
        ('users', '0003_auto_20190924_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postalCode',
            field=models.ForeignKey(default=45200, on_delete=django.db.models.deletion.CASCADE, related_name='postalCode_id', to='postalcode.PostalCode'),
            preserve_default=False,
        ),
    ]
