# Generated by Django 2.2.5 on 2019-09-27 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190927_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
