# Generated by Django 2.2.5 on 2019-09-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190927_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
