# Generated by Django 2.2.5 on 2019-09-27 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postalcode', '0002_auto_20190927_0428'),
        ('events', '0005_auto_20190927_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='postalCode',
            field=models.ForeignKey(default=45000, on_delete=django.db.models.deletion.CASCADE, to='postalcode.PostalCode'),
            preserve_default=False,
        ),
    ]
