# Generated by Django 2.2.6 on 2019-10-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20191006_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventassistance',
            old_name='user',
            new_name='username',
        ),
    ]
